name: main
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout
          uses: actions/checkout@v2
          #with:
            #repository: rpania30/jsonex
            #submodules: 'true'
            #path: './depencies/vtk'
            #ref: 83cd2edafbca4438abee6542162ab206ad3fedd8
        - name: Set up JDK 8
          uses: actions/setup-java@v3
          with:
            java-version: '8'
            distribution: 'adopt'
            cache: maven
        - run: mvn test-compile -pl servicecomb-java-chassis -am
        - run: mvn -pl servicecomb-java-chassis test -Dtest=org.apache.servicecomb.foundation.vertx.http.TestVertxServerRequestToHttpServletRequest#setParameter
        - run: mvn -pl servicecomb-java-chassis edu.illinois:nondex-maven-plugin:1.1.2:nondex -Dtest=org.apache.servicecomb.foundation.vertx.http.TestVertxServerRequestToHttpServletRequest#setParameter
